Models/Invoice.cs
namespace CelsiaProject.Models;

public class Invoice
{
    public required string Id { get; set; }

    public required string Period { get; set; }
    
    public required int InvoicedAmount { get; set; }

    public required int AmountPaid { get; set; }
}

Controllers/InvoicesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CelsiaProject.Data;
using CelsiaProject.Models;
using CelsiaProject.Services;

public class InvoicesController : Controller
{
    private readonly CelsiaContext _context;

    private readonly IInvoicesRepository _invoicesRepository;

    public InvoicesController(CelsiaContext context, IInvoicesRepository invoicesRepository)
    {
        _context = context;
        _invoicesRepository = invoicesRepository;
    }

    public async Task<IActionResult> Index()
    {
        try
        {
            return View(await _context.Invoices.ToListAsync());
        }
        catch
        {
            return ViewBag.Error = "Error al listar las transacciones";
        }
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(Invoice invoice)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }

        try
        {
            _invoicesRepository.AddInvoice(invoice);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        catch
        {
            return View(invoice);
        }
    }
}

Views/Invoices/Create.cshtml
@model CelsiaProject.Models.Invoice

<body>
    <div class="row justify-content-center mt-3">
        <div class="col-md-8">
            <div class="card p-4 bg-dark text-light">
                <h2 class="text-center">Create Invoice</h2>
                <form asp-controller="Invoices" asp-action="Create" method="post">

                    <div class="row mt-3">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group mb-2">
                            <label class="form-label" asp-for="Id">Id</label>
                            <input asp-for="Id" type="text" class="form-control" />
                            <span asp-validation-for="Id" class="text-danger"></span>
                        </div>

                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group mb-2">
                            <label class="form-label" asp-for="Period">Period</label>
                            <input asp-for="Period" type="text" class="form-control" />
                            <span asp-validation-for="Period" class="text-danger"></span>
                        </div>

                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group mb-2">
                            <label class="form-label" asp-for="InvoicedAmount">Invoiced Amount</label>
                            <input asp-for="InvoicedAmount" type="number" class="form-control" />
                            <span asp-validation-for="InvoicedAmount" class="text-danger"></span>
                        </div>

                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group mb-2">
                            <label class="form-label" asp-for="AmountPaid">Amount Paid</label>
                            <input asp-for="AmountPaid" type="number" class="form-control" />
                            <span asp-validation-for="AmountPaid" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group text-center mt-3">
                        <input type="submit" class="btn btn-success form-control" value="Create">
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

Views/Invoices/Index.cshtml
<div class="container">
    <div class="row justify-content-center text-center mb-4 mt-3">
        <div class="col-md-2">
            <a type="button" class="btn btn-success" asp-controller="Invoices" asp-action="Create">Add Invoice</a>
        </div>
        <div class="col-md-8">
            <form asp-controller="Invoices" asp-action="Search" method="get">
                <div class="input-group">
                    <input placeholder="Buscar" class="form-control" name="searchString" aria-describedby="id">
                    <button type="submit" class="btn btn-secondary" id="id">Buscar</button>
                </div>
            </form>
        </div>
    </div>

    <div class="text-center">
        <h1>Invoices</h1>
    </div>

    <table class="table mt-3">
        <thead class="table table-dark">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Period</th>
                <th scope="col">Invoiced Amount</th>
                <th scope="col">AmountPaid</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var customer in Model)
            {
                <tr>
                    <td>@customer.Id</td>
                    <td>@customer.Period</td>
                    <td>$@customer.InvoicedAmount</td>
                    <td>$@customer.AmountPaid</td>
                </tr>
            }
        </tbody>
    </table>
</div>