Controllers/TransactionsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CelsiaProject.Data;
using CelsiaProject.Models;
using CelsiaProject.Services;

public class TransactionsController : Controller
{
    private readonly ITransactionRepository _transactionRepository;

    private readonly CelsiaContext _context;

    public TransactionsController(ITransactionRepository transactionRepository, CelsiaContext context)
    {
        _transactionRepository = transactionRepository;
        _context = context;
    }

    public async Task<IActionResult> Index()
    {
        try
        {
            return View(await _context.Transactions.ToListAsync());
        }
        catch
        {
            return ViewBag.Error = "Error al listar las transacciones";
        }
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(Transaction transaction)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }

        try
        {
            _transactionRepository.AddTransaction(transaction);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        catch
        {
            return View(transaction);
        }
    }
}

Views/Transactions/Create.cshtml
@model CelsiaProject.Models.Transaction

<body>
    <div class="row justify-content-center mt-3">
        <div class="col-md-8">
            <div class="card p-4 bg-dark text-light">
                <h2 class="text-center">Create Transaction</h2>
                <form asp-controller="Transactions" asp-action="Create" method="post">

                    <div class="row mt-3">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group mb-2">
                            <label class="form-label" asp-for="Id">Id</label>
                            <input asp-for="Id" type="text" class="form-control" />
                            <span asp-validation-for="Id" class="text-danger"></span>
                        </div>

                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group mb-2">
                            <label class="form-label" asp-for="DateTime">DateTime</label>
                            <input asp-for="DateTime" type="datetime-local" class="form-control" />
                            <span asp-validation-for="DateTime" class="text-danger"></span>
                        </div>

                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group mb-2">
                            <label class="form-label" asp-for="Amount">Amount</label>
                            <input asp-for="Amount" type="number" class="form-control" />
                            <span asp-validation-for="Amount" class="text-danger"></span>
                        </div>

                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group mb-2">
                            <label class="form-label" asp-for="Status">Status</label>
                            <select name="Status" id="Status" class="form-control">
                                <option value="Pendiente">Pendiente</option>
                                <option value="Completada">Completada</option>
                                <option value="Fallida">Fallida</option>
                            </select>
                            <span asp-validation-for="Status" class="text-danger"></span>
                        </div>

                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group mb-2">
                            <label class="form-label" asp-for="Type">Type</label>
                            <select name="Type" id="Type" class="form-control">
                                <option value="Pago de Factura">Pago de Factura</option>
                            </select>
                            <span asp-validation-for="Type" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="form-group text-center mt-3">
                        <input type="submit" class="btn btn-success form-control" value="Create">
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

Views/Transactions/Index.cshtml
<div class="container">
    <div class="row justify-content-center text-center mb-4 mt-3">
        <div class="col-md-2">
            <a type="button" class="btn btn-success" asp-controller="Transactions" asp-action="Create">Add Transaction</a>
        </div>
        <div class="col-md-8">
            <form asp-controller="Transactions" asp-action="Search" method="get">
                <div class="input-group">
                    <input placeholder="Buscar" class="form-control" name="searchString" aria-describedby="id">
                    <button type="submit" class="btn btn-secondary" id="id">Buscar</button>
                </div>
            </form>
        </div>
    </div>

    <div class="text-center">
        <h1>Transactions</h1>
    </div>

    <table class="table mt-3">
        <thead class="table table-dark">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">DateTime</th>
                <th scope="col">Amount</th>
                <th scope="col">Status</th>
                <th scope="col">Type</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var transaction in Model)
            {
                <tr>
                    <td>@transaction.Id</td>
                    <td>@transaction.DateTime</td>
                    <td>$@transaction.Amount</td>
                    <td>@transaction.Status</td>
                    <td>@transaction.Type</td>
                </tr>
            }
        </tbody>
    </table>
</div>