Models/Customer.cs
namespace CelsiaProject.Models;

public class Customer
{
    public int Id { get; set; }

    public required string Name { get; set; }

    public required string Document { get; set; }

    public required string Address { get; set; }

    public required string PhoneNumber { get; set; }

    public required string Email { get; set; }

    public required string UsedPlatform { get; set; }
}

Controllers/CustomersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CelsiaProject.Data;
using CelsiaProject.Models;
using CelsiaProject.Services;

public class CustomersController : Controller
{
    private readonly CelsiaContext _context;

    public CustomersController(CelsiaContext context)
    {
        _context = context;
    }

    public async Task<IActionResult> Index()
    {
        try
        {
            return View(await _context.Customers.ToListAsync());
        }
        catch
        {
            return ViewBag.Error = "Error al listar las transacciones";
        }
    }
}

Views/Customers/Index.cshtml
<div class="container">
    <div class="row justify-content-center text-center mb-4 mt-3">
        <div class="col-md-2">
            <a type="button" class="btn btn-success" asp-controller="Customers" asp-action="Create">Add Customer</a>
        </div>
        <div class="col-md-8">
            <form asp-controller="Customers" asp-action="Search" method="get">
                <div class="input-group">
                    <input placeholder="Buscar" class="form-control" name="searchString" aria-describedby="id">
                    <button type="submit" class="btn btn-secondary" id="id">Buscar</button>
                </div>
            </form>
        </div>
    </div>

    <div class="text-center">
        <h1>Customers</h1>
    </div>

    <table class="table mt-3">
        <thead class="table table-dark">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Document</th>
                <th scope="col">Address</th>
                <th scope="col">Phone Number</th>
                <th scope="col">Email</th>
                <th scope="col">Used Platform</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var customer in Model)
            {
                <tr>
                    <td>@customer.Id</td>
                    <td>@customer.Name</td>
                    <td>@customer.Document</td>
                    <td>@customer.Address</td>
                    <td>@customer.PhoneNumber</td>
                    <td>@customer.PhoneNumber</td>
                    <td>@customer.UsedPlatform</td>
                </tr>
            }
        </tbody>
    </table>
</div>